spring:
  banner:
    location: classpath:banner-test.txt
  datasource:
    url: jdbc:h2:mem:db
    username: h2
    password: h2
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
